########################################################
########################################################
# @TODO: Hamza -- Make proper distinction between 
#
# Values.name
# Values.container.name

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name}}
  labels:
    group: {{ .Values.group }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
